title: "Data Sciencing"
email: annalallen6@gmail.com
description: "Hey everyon! I'm here to explain some of the basics of Data Science. I've learned that in teaching we learn, and I'm always in need of some learning."
url: https://annleealbod.github.io
author: Anna Bodily
copyright: AB
footer_description: Thanks for reading.
